project_id = "ypbdxgcumtbtfknpoykp"

[functions.manage-tasks]
verify_jwt = false

[functions.manage-customers]
verify_jwt = false

[functions.record-lead-sent]
verify_jwt = false

[functions.manage-pat]
verify_jwt = false

[functions.send-channel-message]
verify_jwt = false

[functions.send-task-notifications]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.outreach-add-entry]
verify_jwt = false

[functions.outreach-delete-old]
verify_jwt = false

[functions.deliver-crm-webhooks]
verify_jwt = false

[functions.manage-crm-followups]
verify_jwt = false

[functions.crm-leads]
verify_jwt = false

[functions.crm-stages]
verify_jwt = false

[functions.crm-sources]
verify_jwt = false

[functions.crm-webhooks]
verify_jwt = false

[functions.crm-webhook-events]
verify_jwt = false
